#include "src/game/envfx_snow.h"

const GeoLayout squishy_plush_pet_Anim_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(0, geo_mirror_mario_set_alpha),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 17, 0, squishy_plush_pet_Body_mesh_layer_1_mat_override_pet_basic_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_plush_pet_Body_mesh_layer_5_mat_override_pet_basic_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_plush_pet_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 178, 60),
		GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(0, geo_mirror_mario_set_alpha),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_anim_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 17, 0, squishy_plush_pet_Body_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_plush_pet_Body_mesh_layer_5),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_BRANCH(1, squishy_plush_pet_Anim_State_Switch_opt1),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
				GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
