extern const GeoLayout squishy_card_geo[];
extern Lights1 squishy_card_Front_layer5_lights;
extern Lights1 squishy_card_Back_layer5_lights;
extern u8 squishy_card_squishy_balatro_card_full_ci8[];
extern u8 squishy_card_squishy_balatro_card_full_pal_rgba16[];
extern u8 squishy_card_squishy_balatro_card_full_back_ci4[];
extern u8 squishy_card_squishy_balatro_card_full_back_pal_rgba16[];
extern Vtx squishy_card_squishy_card_mesh_layer_5_vtx_cull[8];
extern Vtx squishy_card_squishy_card_mesh_layer_5_vtx_0[4];
extern Gfx squishy_card_squishy_card_mesh_layer_5_tri_0[];
extern Vtx squishy_card_squishy_card_mesh_layer_5_vtx_1[4];
extern Gfx squishy_card_squishy_card_mesh_layer_5_tri_1[];
extern Gfx mat_squishy_card_Front_layer5[];
extern Gfx mat_revert_squishy_card_Front_layer5[];
extern Gfx mat_squishy_card_Back_layer5[];
extern Gfx mat_revert_squishy_card_Back_layer5[];
extern Gfx squishy_card_squishy_card_mesh_layer_5[];
