#include "src/game/envfx_snow.h"

const GeoLayout squishy_hair_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),
		GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_OPAQUE_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),
		GEO_ASM(0, geo_mirror_mario_set_alpha),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, -1, squishy_hair_0000_displaylist_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_hair_material_revert_render_settings),
		GEO_CLOSE_NODE(),
		GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_OPAQUE_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
		GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
