const GeoLayout squishy_Capless_Head[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, squishy_geo_opt_1_1),
			GEO_BRANCH(1, squishy_geo_opt_2_1),
			GEO_BRANCH(1, squishy_geo_opt_3_1),
			GEO_BRANCH(1, squishy_geo_opt_4_1),
			GEO_BRANCH(1, squishy_geo_opt_5_1),
			GEO_BRANCH(1, squishy_geo_opt_6_1),
			GEO_BRANCH(1, squishy_geo_opt_7_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_with_layer_4_revert),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Capless_Head_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Switch_optionnnn_please_work_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Left_Hand_Open_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Switch_optionnnn_please_work_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Open_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Peace_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Cap_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4_with_layer_4_revert_with_layer_4_revert),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Metal_Squishy[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 70, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_SCALE(LAYER_FORCE, 39751),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Switch_optionnnn_please_work_Butt_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_move_mario_part_from_parent),
							GEO_ASM(0, geo_mario_tilt_torso),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 32, 0, 0, squishy_Switch_optionnnn_please_work_Torso_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 145, 8, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_head_rotation),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Switch_optionnnn_please_work_Head_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Capless_Head_002),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 182, 1, 80, -15, 33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Switch_optionnnn_please_work_Left_Wing_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_FORCE, 182, 1, -80, 15, -33, -133),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
												GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Switch_optionnnn_please_work_Right_Wing_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -10, 78, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Switch_optionnnn_please_work_Left_Arm_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, -3, squishy_Switch_optionnnn_please_work_Left_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(1, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, -3, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Switch_optionnnn_please_work_Left_Hand_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Left_Hand_Open_002),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -10, -78, NULL),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Switch_optionnnn_please_work_Right_Arm_Color_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 3, squishy_Switch_optionnnn_please_work_Right_Forearm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_hand),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 3, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Switch_optionnnn_please_work_Right_Hand_DL_mesh_layer_1),
															GEO_CLOSE_NODE(),
															GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Open_002),
													GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Peace_002),
													GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Cap_002),
													GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_002),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -88, 5, 54, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Switch_optionnnn_please_work_Left_Thigh_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 130, -1, 0, squishy_Switch_optionnnn_please_work_Left_Leg_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 127, -7, 5, squishy_Switch_optionnnn_please_work_Left_Shoe_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, -88, 5, -54, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Switch_optionnnn_please_work_Right_Thigh_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 130, -1, 0, squishy_Switch_optionnnn_please_work_Right_Leg_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 127, -7, -5, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(2, geo_mario_hand_foot_scaler),
											GEO_SCALE(LAYER_FORCE, 65536),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Switch_optionnnn_please_work_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert_with_layer_1_revert),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, squishy_geo_opt_1_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_2_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_3_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_4_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_5_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_6_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_7_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2_opt_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2_opt_1_opt_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2_opt_1_opt_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2_opt_1_opt_4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2_opt_1_opt_5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2_opt_1_opt_6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2_opt_1_opt_7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Capless_Head_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, squishy_geo_opt_1_1_opt_1),
			GEO_BRANCH(1, squishy_geo_opt_2_1_opt_1),
			GEO_BRANCH(1, squishy_geo_opt_3_1_opt_1),
			GEO_BRANCH(1, squishy_geo_opt_4_1_opt_1),
			GEO_BRANCH(1, squishy_geo_opt_5_1_opt_1),
			GEO_BRANCH(1, squishy_geo_opt_6_1_opt_1),
			GEO_BRANCH(1, squishy_geo_opt_7_1_opt_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_2_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_3_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_4_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_5_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_6_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_7_1_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Capless_Head_Switch_Option_Capless_Head_mesh_layer_4_opt_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Left_Hand_Open_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Open_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Peace_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Cap_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Right_Hand_Wing_Cap_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_4),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 70, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_TRANSPARENT, 39751),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Butt_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 32, 0, 0, squishy_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Torso_mesh_layer_4),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 145, 8, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Head_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, squishy_geo_opt_1_2_opt_1_opt_1),
												GEO_BRANCH(1, squishy_geo_opt_1_2_opt_1_opt_2),
												GEO_BRANCH(1, squishy_geo_opt_1_2_opt_1_opt_3),
												GEO_BRANCH(1, squishy_geo_opt_1_2_opt_1_opt_4),
												GEO_BRANCH(1, squishy_geo_opt_1_2_opt_1_opt_5),
												GEO_BRANCH(1, squishy_geo_opt_1_2_opt_1_opt_6),
												GEO_BRANCH(1, squishy_geo_opt_1_2_opt_1_opt_7),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_Capless_Head_opt_1),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 182, 1, 80, -15, 33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Left_Wing_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 182, 1, -80, 15, -33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Right_Wing_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, -10, 78, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, -3, squishy_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, -3, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, squishy_Left_Hand_Open_opt_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, -10, -78, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Right_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 3, squishy_Right_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 3, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, squishy_Right_Hand_Open_opt_1),
											GEO_BRANCH(1, squishy_Right_Hand_Peace_opt_1),
											GEO_BRANCH(1, squishy_Right_Hand_Cap_opt_1),
											GEO_BRANCH(1, squishy_Right_Hand_Wing_Cap_opt_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -88, 5, 54, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Left_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 130, -1, 0, squishy_Left_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, -7, 5, squishy_Left_Shoe_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -88, 5, -54, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Right_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 130, -1, 0, squishy_Right_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, -7, -5, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_TRANSPARENT, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Capless_Head_002_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Capless_Head_Switch_Option_Capless_Head_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Left_Hand_Open_002_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Switch_optionnnn_please_work_Left_Hand_Open_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Open_002_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Peace_002_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Peace_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Cap_002_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Cap_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_002_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 0, squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_Swtich_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_Swtich_Option_Wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo_opt_1_3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_TRANSPARENT, 39751),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Switch_optionnnn_please_work_Butt_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_move_mario_part_from_parent),
					GEO_ASM(0, geo_mario_tilt_torso),
					GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 32, 0, 0, squishy_Switch_optionnnn_please_work_Torso_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 145, 8, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_mario_head_rotation),
								GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Head_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Capless_Head_002_opt_1),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 182, 1, 80, -15, 33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Left_Wing_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_TRANSPARENT, 182, 1, -80, 15, -33, -133),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
										GEO_ROTATION_NODE(LAYER_TRANSPARENT, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Right_Wing_DL_mesh_layer_4),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, -10, 78, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Switch_optionnnn_please_work_Left_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, -3, squishy_Switch_optionnnn_please_work_Left_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(1, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, -3, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Left_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Left_Hand_Open_002_opt_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 72, -10, -78, NULL),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Switch_optionnnn_please_work_Right_Arm_Color_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 3, squishy_Switch_optionnnn_please_work_Right_Forearm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_TRANSPARENT, 109, 0, 3, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_hand_foot_scaler),
													GEO_SCALE(LAYER_TRANSPARENT, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Right_Hand_DL_mesh_layer_1),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Open_002_opt_1),
											GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Peace_002_opt_1),
											GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Cap_002_opt_1),
											GEO_BRANCH(1, squishy_Switch_optionnnn_please_work_Right_Hand_Wing_Cap_002_opt_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -88, 5, 54, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Switch_optionnnn_please_work_Left_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 130, -1, 0, squishy_Switch_optionnnn_please_work_Left_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, -7, 5, squishy_Switch_optionnnn_please_work_Left_Shoe_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -88, 5, -54, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, squishy_Switch_optionnnn_please_work_Right_Thigh_Color_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 130, -1, 0, squishy_Switch_optionnnn_please_work_Right_Leg_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 127, -7, -5, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(2, geo_mario_hand_foot_scaler),
									GEO_SCALE(LAYER_TRANSPARENT, 65536),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_Switch_optionnnn_please_work_Right_Shoe_DL_mesh_layer_1_with_layer_5_revert_with_layer_5_revert),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 27012),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_OPAQUE + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_OPAQUE_DECAL + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_ALPHA + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_TRANSPARENT + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_TRANSPARENT_DECAL + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_OPAQUE << 2, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_OPAQUE_DECAL << 2, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_ALPHA << 2, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_TRANSPARENT << 2, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ LAYER_TRANSPARENT_DECAL << 2, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 70, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_SCALE(LAYER_FORCE, 39751),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Butt_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_move_mario_part_from_parent),
											GEO_ASM(0, geo_mario_tilt_torso),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 32, 0, 0, squishy_Torso_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Torso_mesh_layer_4),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 145, 8, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_head_rotation),
														GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Head_DL_mesh_layer_1),
																			GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Head_DL_mesh_layer_4),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, squishy_geo_opt_1),
																		GEO_BRANCH(1, squishy_geo_opt_2),
																		GEO_BRANCH(1, squishy_geo_opt_3),
																		GEO_BRANCH(1, squishy_geo_opt_4),
																		GEO_BRANCH(1, squishy_geo_opt_5),
																		GEO_BRANCH(1, squishy_geo_opt_6),
																		GEO_BRANCH(1, squishy_geo_opt_7),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, squishy_Capless_Head),
															GEO_CLOSE_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_FORCE, 182, 1, 80, -15, 33, -133),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
																GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Left_Wing_DL_mesh_layer_4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_TRANSLATE_ROTATE(LAYER_FORCE, 182, 1, -80, 15, -33, -133),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
																GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_Right_Wing_DL_mesh_layer_4),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 71, -10, 78, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Left_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, -3, squishy_Left_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, -3, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(1, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Left_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, squishy_Left_Hand_Open),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 72, -10, -78, NULL),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Right_Arm_Color_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 3, squishy_Right_Forearm_mesh_layer_1),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(LAYER_OPAQUE, 109, 0, 3, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(0, geo_mario_hand_foot_scaler),
																			GEO_SCALE(LAYER_FORCE, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Right_Hand_DL_mesh_layer_1),
																			GEO_CLOSE_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, squishy_Right_Hand_Open),
																	GEO_BRANCH(1, squishy_Right_Hand_Peace),
																	GEO_BRANCH(1, squishy_Right_Hand_Cap),
																	GEO_BRANCH(1, squishy_Right_Hand_Wing_Cap),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -88, 5, 54, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Left_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 130, -1, 0, squishy_Left_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 127, -7, 5, squishy_Left_Shoe_mesh_layer_1),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, -88, 5, -54, NULL),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, squishy_Right_Thigh_Color_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 130, -1, 0, squishy_Right_Leg_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 127, -7, -5, NULL),
														GEO_OPEN_NODE(),
															GEO_ASM(2, geo_mario_hand_foot_scaler),
															GEO_SCALE(LAYER_FORCE, 65536),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_Right_Shoe_DL_mesh_layer_1_with_layer_1_revert),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, squishy_geo_opt_1_2),
							GEO_BRANCH(1, squishy_Metal_Squishy),
							GEO_BRANCH(1, squishy_Metal_Squishy),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ (LAYER_OPAQUE << 2) | 1, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ (LAYER_OPAQUE_DECAL << 2) | 1, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ (LAYER_ALPHA << 2) | 1, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ (LAYER_TRANSPARENT << 2) | 1, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_FORCE, 0, 70, 0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ASM(/*Draw Layer*/ (LAYER_TRANSPARENT_DECAL << 2) | 1, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
