const GeoLayout squishy_cap_metal_wing_geo_opt_1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_cap_metal_wing_Winged_Metal_Cap_DL_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, squishy_cap_metal_wing_Winged_Metal_Cap_DL_mesh_layer_1_with_layer_5_revert),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout squishy_cap_metal_wing_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(/*Draw Layer*/ LAYER_FORCE + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_ASM(/*Draw Layer*/ LAYER_FORCE + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_ASM(/*Draw Layer*/ LAYER_FORCE + 3, /*Function*/ geo_mario_set_player_colors),
				GEO_ASM(/*Draw Layer*/ LAYER_FORCE << 2, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_ASM(/*Draw Layer*/ LAYER_FORCE << 2, /*Function*/ geo_mirror_mario_backface_culling),
				GEO_ASM(10, geo_update_layer_transparency),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, squishy_cap_metal_wing_Winged_Metal_Cap_DL_mesh_layer_4_with_layer_4_revert),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, squishy_cap_metal_wing_Winged_Metal_Cap_DL_mesh_layer_1_with_layer_1_revert),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, squishy_cap_metal_wing_geo_opt_1),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
