extern const GeoLayout squishy_tutorial_area_1_geo[];
extern const GeoLayout squishy_tutorial_area_1[];
extern const Collision squishy_tutorial_area_1_collision[];
extern const MacroObject squishy_tutorial_area_1_macro_objs[];
extern Lights1 squishy_tutorial_dl_Blue_Grass_lights;
extern Lights1 squishy_tutorial_dl_Red_Stone_lights;
extern u8 squishy_tutorial_dl_blue_grass_rgba16[];
extern u8 squishy_tutorial_dl_red_cliff_rgba16[];
extern Vtx squishy_tutorial_dl_Ground_Test_mesh_layer_1_vtx_cull[8];
extern Vtx squishy_tutorial_dl_Ground_Test_mesh_layer_1_vtx_0[30];
extern Gfx squishy_tutorial_dl_Ground_Test_mesh_layer_1_tri_0[];
extern Vtx squishy_tutorial_dl_Ground_Test_mesh_layer_1_vtx_1[41];
extern Gfx squishy_tutorial_dl_Ground_Test_mesh_layer_1_tri_1[];
extern Gfx mat_squishy_tutorial_dl_Blue_Grass[];
extern Gfx mat_revert_squishy_tutorial_dl_Blue_Grass[];
extern Gfx mat_squishy_tutorial_dl_Red_Stone[];
extern Gfx mat_revert_squishy_tutorial_dl_Red_Stone[];
extern Gfx squishy_tutorial_dl_Ground_Test_mesh_layer_1[];
