extern const GeoLayout squishy_slide_spark_geo[];
extern Lights0 squishy_slide_spark_Fast3D_Material_lights;
extern u8 squishy_slide_spark_squishy_slide_burn_ci4[];
extern u8 squishy_slide_spark_squishy_slide_burn_pal_rgba16[];
extern Vtx squishy_slide_spark_Cone_mesh_layer_5_vtx_0[15];
extern Gfx squishy_slide_spark_Cone_mesh_layer_5_tri_0[];
extern Gfx mat_squishy_slide_spark_Fast3D_Material[];
extern Gfx mat_revert_squishy_slide_spark_Fast3D_Material[];
extern Gfx squishy_slide_spark_Cone_mesh_layer_5[];
extern Gfx squishy_slide_spark_material_revert_render_settings[];
